apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"hellopython","pipeline.openshift.io/runtime":"python","pipeline.openshift.io/type":"kubernetes"},"name":"hellopython","namespace":"mytest"},"spec":{"params":[{"default":"hellopython","name":"APP_NAME","type":"string"},{"default":"https://github.com/rrs8/hellopython.git","name":"GIT_REPO","type":"string"},{"default":"master","name":"GIT_REVISION","type":"string"},{"default":"image-registry.openshift-image-registry.svc:5000/hello/hellopython","name":"IMAGE_NAME","type":"string"},{"default":".","name":"PATH_CONTEXT","type":"string"},{"default":"3.8-ubi8","name":"VERSION","type":"string"}],"tasks":[{"name":"fetch-repository","params":[{"name":"url","value":"$(params.GIT_REPO)"},{"name":"revision","value":"$(params.GIT_REVISION)"},{"name":"deleteExisting","value":"true"}],"taskRef":{"kind":"ClusterTask","name":"git-clone"},"workspaces":[{"name":"output","workspace":"workspace"}]},{"name":"build","params":[{"name":"IMAGE","value":"$(params.IMAGE_NAME)"},{"name":"TLSVERIFY","value":"false"},{"name":"PATH_CONTEXT","value":"$(params.PATH_CONTEXT)"},{"name":"VERSION","value":"$(params.VERSION)"}],"runAfter":["fetch-repository"],"taskRef":{"kind":"ClusterTask","name":"s2i-python"},"workspaces":[{"name":"source","workspace":"workspace"}]},{"name":"sysdigscan","params":[{"name":"IMAGE","value":"$(params.IMAGE_NAME)"}],"runAfter":["build"],"taskRef":{"kind":"Task","name":"sysdigscan"}}],"workspaces":[{"name":"workspace"}]}}
  creationTimestamp: "2022-01-05T22:55:02Z"
  generation: 5
  labels:
    app.kubernetes.io/instance: hellopython
    pipeline.openshift.io/runtime: python
    pipeline.openshift.io/type: kubernetes
  managedFields:
  - apiVersion: tekton.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:resources: {}
    manager: Mozilla
    operation: Update
    time: "2022-01-06T02:28:39Z"
  - apiVersion: tekton.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:pipeline.openshift.io/runtime: {}
          f:pipeline.openshift.io/type: {}
      f:spec:
        .: {}
        f:params: {}
        f:tasks: {}
        f:workspaces: {}
    manager: oc
    operation: Update
    time: "2022-01-06T02:39:55Z"
  name: hellopython
  namespace: mytest
  resourceVersion: "3150020"
  selfLink: /apis/tekton.dev/v1beta1/namespaces/mytest/pipelines/hellopython
  uid: 9fa64344-f44e-4443-9596-668c98e5425f
spec:
  params:
  - default: hellopython
    name: APP_NAME
    type: string
  - default: https://github.com/rrs8/hellopython.git
    name: GIT_REPO
    type: string
  - default: main
    name: GIT_REVISION
    type: string
  - default: image-registry.openshift-image-registry.svc:5000/mytest/hellopython
    name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: 3.8-ubi8
    name: VERSION
    type: string
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: sysdigscan
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    runAfter:
    - buildah
    taskRef:
      kind: Task
      name: sysdigscan
  - name: buildah
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Dockerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "false"
    - name: FORMAT
      value: oci
    runAfter:
    - fetch-repository
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  workspaces:
  - name: workspace
