# This is a basic workflow to help you get started with Actions

name: Build and scan Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Build the Docker image
      run: ls; docker build . --tag sysdiglabs/github-actions-example:latest
    - name: Scan image
      id: scan
      uses: sysdiglabs/scan-action@v3
      with:
        image-tag: "sysdiglabs/github-actions-example:latest"
        sysdig-secure-url: https://us2.app.sysdig.com/
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        input-type: docker-daemon
        run-as-user: root
