#
# Sysdig Image Scan tekton task
# 
# Can be added directly to an OpenShift pipeline after installation steps below:
#    1) oc apply -f <this file>
#    2) add Sysdig Secure API token using sysdig-secrets.sh
#    3) add the "sysdigscan" task to the openshift pipeline
#    4) there will be a red '!' on the sysdigscan task for a missing input
#    5) click on the task and set the value 'IMAGE' to the right pipeline parameter e.g. $(params.IMAGE_NAME)
#    
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sysdigscan
spec:
  params:
    - name: IMAGE
      description: image to scan
  steps:
    - name: scan
      image: quay.io/sysdig/secure-inline-scan:2
      args:
        - --registry-skip-tls
        - --registry-auth-file
        - /tekton/creds/.docker/config.json
        - -s
        - https://us2.app.sysdig.com
        - $(params.IMAGE)
      env:
        - name: SYSDIG_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: sysdig-secrets
              key: sysdig-secure-api-token
        - name: http_proxy
          value: "http://44.201.174.60:3128"
        - name: https_proxy
          value: "http://44.201.174.60:3128"
        - name: no_proxy
          value: "image-registry.openshift-image-registry.svc"
