#
# Sysdig Tekton Pipeline - Dockerfile
#  - uses buildah to build an image from Dockerfile
#  - Sysdig scans the image for vulnerabilities
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hellopython-dockerfile
  labels:
    app.kubernetes.io/instance: hellopython-dockerfile
    pipeline.openshift.io/runtime: python
    pipeline.openshift.io/type: kubernetes
spec:
  params:
  - default: hellopython
    name: APP_NAME
    type: string
  - default: https://github.com/rrs8/hellopython.git
    name: GIT_REPO
    type: string
  - default: main
    name: GIT_REVISION
    type: string
  - default: image-registry.openshift-image-registry.svc:5000/hello/hellopython
    name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: 3.8-ubi8
    name: VERSION
    type: string
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: sysdigscan
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    runAfter:
    - buildah
    taskRef:
      kind: Task
      name: sysdigscan
  - name: buildah
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Dockerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "false"
    - name: FORMAT
      value: oci
    runAfter:
    - fetch-repository
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  workspaces:
  - name: workspace
