apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hellopython-dockerfile-pr-
  labels:
    app.kubernetes.io/instance: hellopython-dockerfile
    pipeline.openshift.io/runtime: python
    pipeline.openshift.io/type: kubernetes
    tekton.dev/pipeline: hellopython-dockerfile
spec:
  params:
  - name: APP_NAME
    value: hellopython
  - name: GIT_REPO
    value: https://github.com/rrs8/hellopython.git
  - name: GIT_REVISION
    value: main
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/hello/hellopython
  - name: PATH_CONTEXT
    value: .
  - name: VERSION
    value: 3.8-ubi8
  pipelineRef:
    name: hellopython-dockerfile
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          labels:
            tekton.dev/pipeline: hellopython-dockerfile
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
