#
# Sysdig image scan requires a valid Sysdig Secure API Token
# This is available in the Sysdig UI under Settings (select the circle with your initials in lower right)
#   in the first settings screen (User Profile) in the section Sysdig Secure API
#
# For the api token below it must be base64 encoded:
#    echo -n <SYSDIG_API_TOKEN> | base64
# Use the value returned as <YOUR_SECRET_HERE_IN_BASE64> below
#
apiVersion: v1
data:
  sysdig-secure-api-token: ${YOUR_SECRET_HERE_IN_BASE64}
kind: Secret
metadata:
  creationTimestamp: null
  name: sysdig-secrets
