apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sysdigscan
spec:
  params:
    - name: IMAGE
      description: image to scan
  steps:
    - name: scan
      image: quay.io/sysdig/secure-inline-scan:2
      args:
        - --registry-skip-tls
        - --registry-auth-file
        - /tekton/creds/.docker/config.json
        - -s
        - https://us2.app.sysdig.com
        - $(params.IMAGE)
      env:
        - name: SYSDIG_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: sysdig-secrets
              key: sysdig-secure-api-token
        - name: http_proxy
          value: "http://44.201.174.60:3128"
        - name: https_proxy
          value: "http://44.201.174.60:3128"
        - name: no_proxy
          value: "image-registry.openshift-image-registry.svc"
