apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildscanpush
spec:
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce.
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: vfs
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: IMAGE_PUSH_SECRET_NAME
      description: Kubernetes secrets contain image push username and password
    - name: destinationImage
      description: the fully qualified image name
      default: "$(outputs.resources.builtImage.url)"
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.23.1
      workingDir: $(workspaces.source.path)
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) bud \
          --no-cache -f $(params.DOCKERFILE) -t $(params.IMAGE) .
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        runAsUser: 0
    - name: scan
      image: quay.io/sysdig/secure-inline-scan:2
      workingDir: $(workspaces.source.path)
      args:
        - -v
        - -s
        - https://us2.app.sysdig.com
        - --storage-type 
        - cri-o
        - $(params.IMAGE)
      env:
        - name: SYSDIG_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: sysdig-secrets
              key: sysdig-secure-api-token
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        runAsUser: 0
        privileged: true
    - name: push
      image: quay.io/buildah/stable:v1.23.1
      workingDir: $(workspaces.source.path)
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) push \
          --creds ${USERNAME}:${PASSWORD} $(params.IMAGE)
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        runAsUser: 0
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_PUSH_SECRET_NAME)
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_PUSH_SECRET_NAME)
              key: password
  volumes:
    - name: varlibcontainers
      emptyDir: {}
