apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: no-sysdig-pipeline-
spec:
  pipelineRef:
    name: no-sysdig-pipeline
  workspaces:
    - name: myworkspace
      persistentVolumeClaim:
        claimName: config-artifact-pvc
