apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sysdig-pipeline-
spec:
  pipelineRef:
    name: allin-pipeline
  workspaces:
    - name: myworkspace
      persistentVolumeClaim:
        claimName: config-artifact-pvc
