# This is a basic workflow to help you get started with Actions

name: Build and scan Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: 
       cd githubactions
       docker build . --tag sysdiglabs/github-actions-example:latest
    - name: Scan image
      uses: sysdiglabs/scan-action@v1
      with:
        image-tag: "sysdiglabs/github-actions-example:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
